version: '3'
services:
  app1:
    build: ./app1
    ports:
      - "3001:3001"
    depends_on:
      - app2
    volumes:
      - ./app1:/usr/src/app

  app2:
    build: ./app2
    ports:
      - "3002:3002"
    volumes:
      - ./app2:/usr/src/app
